name: Hospital management website
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker image and Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: hospitaldockerfile
          context: .
          push: true
          tags: lksa/hospital:${{ github.sha }}

      - name: SSH into EC2 Instance and deploy Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SHAKIRAT_HOST }}
          username: ${{ secrets.SHAKIRAT_USERNAME }}
          key: ${{ secrets.SHAKIRAT_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop hospital || true
            docker rm hospital || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hospital:${{ github.sha }}
            sudo docker run -d --name hospital -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/hospital:${{ github.sha }}